### ISSUE TITLE
Not Valid JSON / Encoding

### ISSUE THREAD

**Issue by thedward** [DanFessler/basin#1]
Your examples are not valid JSON. JSON string values must be quoted with double quotes, including keys.

Do you even verfy that the input is encoded with cp-1252?
I

**Comment by DanFessler** [comment]
You're right.  I'm playing fast and loose with the examples as they are being written directly in javascript rather than loaded in as external JSON files.  It simply allows me to not have to deal with the extra noise, but I suppose the examples should be pure JSON to avoid confusion on this.

To clarify, BASON does not parse JSON directly, it assumes you have already parsed it into a Javascript Object.

**Comment by DanFessler** [comment]
updated the examples and language reference.  closing this.
